# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cfb6fcd2b4147cfe40424de041dfa6a9a3204e3822bd32afd48107564f8a9e06d8850ee95b73a5ea68cef2680415fcd5ef69a00c4b5c2ad26e1cbb3138bb025

test:
  secret_key_base: de522160b0ab08214d64c998323c2323836bf17db31647fe8b760e876f98952b98659c5bcebb56d68b0c97babdc84ece6eebe5c3411bd488f489125063d1a214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
